### ISSUE TITLE
Desensitize time step, grid, for children of driver

### ISSUE THREAD

**Issue by mdpiper** [csdms/wmt-client#62]
The driver component of a model sets the time step, simulation length and grid information. Currently, any children coupled to the driver (one-way or two-way) also display these run parameters. They are, however, ignored.

For example, in the screenshot below, **CEM** is the driver, yet **Avulsion** shows run parameters that can edited, yet are ultimately ignored.

![screen shot 2015-07-07 at 3 43 12 pm](https://cloud.githubusercontent.com/assets/5673711/8558118/536e0a14-24bf-11e5-80f0-8c35735e0d7f.png)

It would be less confusing to users if these run parameters on the children were either desensitized or removed entirely.

This idea is from @iovereem.

**Comment by mdpiper** [comment]
The larger issue here is in the data model for **wmt-client** -- the components in the `ModelTree` don't know about each other.

This came up today in a different context: @Elchin notes that in TopoFlow, the **.rti** file required by each component has to be loaded into the parameters for each component individually. It would be better if any child components in a coupled model would inherit the **.rti** file from the driver.

**Comment by Elchin** [comment]
Also, user will have a really hard time to set the required parameters in coupled components because he/she does not know what is in the uses.json file

**Comment by peckhams** [comment]
I remember making a conscious choice to have each TopoFlow component read
in grid information on its own, despite the redundancy.  There is a very
low cost to reading grid info from the RTI file, while requiring all
components to get the RTI info from the driver adds complexity and makes
configurations more fragile.  Since any TopoFlow component is allowed to be
the driver, they all need to be able to read info from an RTI file in any
case.  This change should be given some careful thought.

**Comment by mdpiper** [comment]
Fixed. We implemented "global" parameters, which allow us (CSDMS IF) to choose what parameters are shown in the driver, but are not visible in the forcing components. See 04cf9505506704535c866564c5a0ed2427bde5a7.
